title: Bigstone Courthouse
descrpition: "A collection of laws for the Bigstone server."

lockdown: false

discord: "https://discord.gg/TgbpaAVsMJ"

law-application: "https://forms.gle/j8rxPPrwpbx6UVBWA"

baseurl: "/bigstone-laws"
url: "formalParrot.github.io"
repository: formalParrot/bigstone-laws

# Build settings
theme: minima

# Pages in the header navigation
header_pages:
  - pages/about.md
  - pages/rules.md
  - pages/cases.md
  - pages/events.html

defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout:

#Collections
collections:
  # Law Collection
  laws:
    output: true
    permalink: /laws/:name/
  clauses:
    output: true
    permalink: /laws/clauses/:name/
  subclauses:
    output: true
    permalink: /laws/clauses/subclauses/:name/

  # Case Collection
  cases:
    output: true
    permalink: /cases/:name/
