title: Bigstone Lawbook
descrpition: "A collection of laws for the Bigstone server."

discord: "https://discord.gg/MZ7hBU7GVV"

law-application: "https://forms.gle/j8rxPPrwpbx6UVBWA"

baseurl: "/bigstone-laws"
url: "formalParrot.github.io"
repository: formalParrot/bigstone-laws

# Build settings
theme: minima

# Pages in the header navigation
header_pages:
  - about.md
  - laws.md
  - cases.md
  - events.html


#Collections
collections:
  # Law Collection
  laws:
    output: true
    permalink: /laws/:name/
  clauses:
    output: true
    permalink: /laws/clauses/:name/
  subclauses:
    output: true
    permalink: /laws/clauses/subclauses/:name/

  # Case Collection
  cases:
    output: true
    permalink: /cases/:name/
